### ISSUE TITLE
User can start the game.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#1]
# Motivation

Users need to be able to see the game board and the grid in order to play.

# Tasks

- [x] Create relevant html, css, and javascript files with appropriate links
- [x] Create a landing div, a container to hold content within the margins, and a div to hold the game board
- [x] Display the name of the game at the top of the page
- [x] Use javascript to create 8x8 grid of divs with percentage values for width and height
- [x] Append the game board grid to HTML document
- [x] Create a class to hide the outer row to make the grid 6x6 with a one square perimeter
- [x] Created a "GAME START" button that displays the board and then disappears
