### ISSUE TITLE
Users can start the game. (Refactor)

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#12]
# Motivation

Refactor the way the program renders the board. Rather than keeping all the data in the DOM, this method will store key game data in an object and render the board using relevant data from the object.
![screen shot 2017-06-12 at 9 22 48 pm](https://user-images.githubusercontent.com/29046343/27106798-cd67278a-5049-11e7-9785-e2e7c8e171f0.png)

# Tasks

- [x] Create a function that creates an array of game tile objects with properties for column, row, and isHidden
- [x] Create a function that creates the game board as an array of arrays.
- [x] Create a function for renderTile to take an object from the board and return a tile div.
- [x] Create a function for renderRow that uses renderTile to render the tiles in an entire row grouped in a row div.
- [x] Create a function to render the entire board in a div with rows generated from renderRow
