### ISSUE TITLE
Users will only be given puzzle configurations that are possible to complete.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#18]
# Motivation

If the puzzle includes a section of tiles partitioned off by dead tiles, it may be impossible to complete. Creating a partition checker will allow any boards with partitioned off tiles to be re-randomized to drastically reduce the amount of impossible puzzle configurations.

# Tasks

- [x] Create a function that checks if a set of tile coordinates are contained in an array of tile coordinates
- [x] Create a function that starts at the first non-dead tile and counts all adjacent tiles, spreading outward.
- [x] Write a conditional statement that re-randomizes the board if the number of adjacent live tiles plus the number of dead tiles does not equal the total number of tiles on the board
