### ISSUE TITLE
Users can select select tiles to make moves.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#2]
# Motivation

Users must be able to click on a tile to select a tile. Clicking on the same tile should unselect the tile and clicking on a new tile should switch their contents.

# Tasks

- [x] Add an event listener to the board that captures the data of a tile selected in the board array
- [x] Add a conditional to prevent selecting hidden tiles or row divs
- [x] Create a function that sets isSelected property to true on selected tile
- [x] Create a selected class in CSS to add a different background color
- [x] Re-render the board after each selection
- [x] Create a conditional that detects if two tiles are selected at once and if so, switches the contents of the tiles and deselects both

**Comment by danielduffield** [comment]
https://occs.mybalsamiq.com/projects/occs-nine/short-circuit-issue-2
