### ISSUE TITLE
Visual Update with Improved Sprites for Game Tiles.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#24]
# Motivation

Since the mechanics are in place, the original tile representations can now be swapped with better sprites to give a more satisfying experience for users.

# Tasks

- [x] Replace tiles in images folder with better quality sprites
- [x] Add images for tiles that are charge aligned, spent, and charged
- [x] Redirect the image url to include the chargeStatus before the image to direct to the appropriate sprite
- [x] Add sprites for source and sink, relative to the side of the board they appear on
