### ISSUE TITLE
Visual Update: Title Animation

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#26]
# Motivation

Users will be more likely to remember the name of the game if the title is animated and draws attention.

# Tasks

- [x] Create a function that turns the string title into a series of spans
- [x] Create a function that cycles through the list of spans on a timer and lights up one letter at a time
- [x] Create a function that does the same thing in reverse
- [x] Add a glow animation to the title in between animation sequences
