### ISSUE TITLE
Deploy to Heroku.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#28]
# Motivation

Users should be able to play the game on Heroku rather than installing manually.

# Tasks

- [x] Create a server:
    - [x] Install Express and save as a dependency.
    - [x] Install nodemon and save as a dev dependency.
    - [x] Serve the public folder as static middleware.
- [x] Implement browserify:
    - [x] Install browserify and watchify and save as dev dependencies.
    - [x] Refactor: Break up the main file into module format.
- [x] Organize file structure:
    - [x] Create separate folders for client and server.
    - [x] Create a public folder to be served as static middleware.
- [x] Add to the package.json file:
    - [x] Create the following scripts: 
        - [x] start (node).
        - [x] bundle (browserify).
        - [x] watch:server (nodemon).
        - [x] watch:client (watchify).
- [x] Deploy to Heroku:
    - [x] Add postinstall script to package.json file.
    - [x] Install dotenv as a dependency.
    - [x] Create a .env file to hold app data.
    - [x] Invoke dotenv within index.js.
