### ISSUE TITLE
Users can view the Readme to get relevant app information.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#29]
# Motivation

To help users better understand how to run the app and what technologies the app uses, the readme should contain necessary build instructions and technologies used, as well as a short demonstration.

# Tasks

- [ ] Add the build instructions to the readme file.
- [ ] Fill out the technologies used with version information as contained in the package.json file.
- [ ] Create a gif to demonstrate of the app.
- [ ] Add the gif to the readme.
