### ISSUE TITLE
Users can read how to play the game.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#3]
# Motivation

Before the game begins, the user should have an opportunity to know the fundamental rules of how to play, how to win, and how one loses.

# Tasks

- [x] Create a box with instructions that displays on the start screen
- [x] Render a demo board to be displayed alongside the instructions
- [x] Add to the start button event listener to remove both the instructions and the demo board on clicking the start game button
