### ISSUE TITLE
Users can make a path from the start point to the end point.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#4]
# Motivation

The object of the game is to create a path from the start to the finish. Users must be able to see the value of tiles and make decisions on where to place tiles in order to create this path.

# Tasks

- [x] Create a new property for all tiles called "channels" that includes the two directions through which that tile can channel the current
- [x] Draw a series of images to represent the possible tile channel values
- [x] Create a function that randomizes the channels property for each tile
- [x] Assign images to each different channels property value
- [x] Add to the renderTile/renderRow/renderBoard functions to render the images to the board
- [x] Create a check that disallows the moving of dead tiles
- [x] Create a function that prevents dead tiles from spawning in front of the start and end

**Comment by danielduffield** [comment]
![short-circuit-issue-4](https://user-images.githubusercontent.com/29046343/27193417-987d65d2-51b3-11e7-8a8e-e09265c9186f.png)
