### ISSUE TITLE
Users can see where the puzzle begins and ends.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#5]
# Motivation

The object of the game involves channeling an electrical charge from a start point to an end point. Users must be able to clearly see where the puzzle starts and ends.

# Tasks

- [x] Create a function that compiles all non-corner hidden tiles
- [x] Add a function that randomizes the order of an array
- [x] Create a function that selects a start and end point by popping tiles from a randomized array of tiles
- [x] Create a function that adds "start" and "end" as values of "goal" property to relevant tiles
- [x] Add to renderTile function to add "start-point" and "end-point" classes to tiles with relevant "goal" properties
- [x] Added CSS class selectors for "start-point" and "end-point" with different background colors
- [x] Add a conditional that checks the distance between the two selected points and re-selects the end point if the distance is too small
- [x] Add a visual to indicate to the player the start and end\

**Comment by danielduffield** [comment]
![](https://occs.mybalsamiq.com/projects/occs-nine/short-circuit-issue-5)
