### ISSUE TITLE
Users can see the current position of the charge.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#6]
# Motivation

The difficulty of the game resides in keeping ahead of the electrical charge, which must be properly guided from start to finish. Users must be able to see which grid square currently holds the charge.

# Tasks

- [x] Create a new property for each tile called "chargeStatus" that is an object containing charge status
- [x] Charge object should contain booleans for charged, spent, and chargeAligned
- [x] Refactor channels property to be an object with booleans for each valid channel direction
- [x] Create a function that checks the channels of currently charged space to find the next valid tile to hold charge
- [x] Loop through the function to find the path of all charge aligned tiles
- [x] Create a function that shifts the charge forward one valid tile move
    - [x] Change the tile render to include a check for the booleans in the charge property, setting relevant classes "charged", "spent", and "charge-aligned"
    - [x] Add to CSS styling to include visual styles for each new class
- [x] Create a button to activate function that shifts charge forward for debugging
- [x] Update the tile rendering to show visual effect on all tiles that are charge aligned
- [x] Edit the charge shifting function to remove the charge from the previously charged tile and update the charge object spent property to true
- [x] Refactor findAdjacentTile to allow the charge to move into the end-point
- [x] Add CSS styling/animation for when the end/start points hold the charge

**Comment by danielduffield** [comment]
![screen shot 2017-06-15 at 10 22 40 pm](https://user-images.githubusercontent.com/29046343/27213047-354acf70-5219-11e7-8460-328899cf0fb8.png)

**Comment by danielduffield** [comment]
![charge-mockup](https://user-images.githubusercontent.com/29046343/27213483-ffadcff4-521b-11e7-87d6-cc4c8b3713ac.png)

**Comment by danielduffield** [comment]
![charge-mockup-2](https://user-images.githubusercontent.com/29046343/27213998-f385e790-521e-11e7-8095-054a91194649.png)
