### ISSUE TITLE
Users must complete the puzzle ahead of the timed moving charge.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#7]
# Motivation

As a fundamental part of the challenge of the game, users must stay ahead of the charge as it moves one tile along the charge path every couple seconds. Ideally, this will also include visual cues to show how soon the charge will jump to the next tile.

# Tasks

- [x] Add a timer that pushes the charge once every 4 seconds
- [x] Create a timer display so that the player knows how much time they have before the charge moves
- [x] Hide the now-unneeded push charge button
- [x] Add a condition that quickly moves the charge once a complete path to the end is made
- [x] Insert a conditional statement that stops trying to push the charge once it reaches the end
- [x] Change the timer text based on the current game state
