### ISSUE TITLE
Users should be able to restart the game when it's game over.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#8]
# Motivation

If a game over occurs whether from a win or a loss, the player should be given the option to replay the game.

# Tasks

- [x] REFACTOR
  - [x] Create a game object to contain important game information including the board
  - [x] Redirect references to global variables within functions to game object properties (e.g. board, charge coordinates, etc.)
  - [x] Rename variables start and finish to source and sink to match new game object properties
  - [x] Change references to sourceAndSink joint coordinates to individual game properties source and sink
- [x] Create a function to house the entire game from start to finish
- [x] Add a button that appears when a game over occurs that reads, "Play again?"
- [x] Attach an event listener to the button that will call the function to start a new game
- [x] Append the game restart button to the DOM at the right moment and in the correct position
