### ISSUE TITLE
User should be get visual cues of the charge status in addition to the timer.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/short-circuit#9]
# Motivation

While the charge is moving on the board, it's color should reflect how soon a jump to the next tile will occur. It should change color once per second correlating with the time before its next move.

# Tasks

- [x] Create CSS classes for each phase that the charge will animate through
- [x] Create a function called animateCharge that uses the preset recursive game timer to determine charge phases
- [x] Set the timeout function to check for the previous charge phase class if there is one and remove it if there isn't
- [x] Add the new charge phase class to the current tile render and reset the newly added chargeStatus.chargePhase value
- [x] Add the animateCharge function to be called in the timer function that takes the argument of the timer and animates the charge in sync the with game timer
